name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: A clear and concise description of what uou expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual Behaviour
      description: A clear and concise description of the current behavior.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: How does the current behaviour affect the user?

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
  
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: Share your idea of how to resolve the problem, if you have one.

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
